<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-09-09 10:48

$extensionPath = t3lib_extMgm::extPath('vidi');
$extensionClassesPath = t3lib_extMgm::extPath('vidi') . 'Classes/';
return array(
	'tx_vidi_controller_vidicontroller' => $extensionClassesPath . 'Controller/VidiController.php',
	'tx_vidi_service_griddata_abstractprocessingservice' => $extensionClassesPath . 'Service/GridData/AbstractProcessingService.php',
	'tx_vidi_service_griddata_filedataprocessingservice' => $extensionClassesPath . 'Service/GridData/FileDataProcessingService.php',
	'tx_vidi_service_griddata_tcadataprocessingservice' => $extensionClassesPath . 'Service/GridData/TcaDataProcessingService.php',
	'tx_vidi_service_griddata' => $extensionClassesPath . 'Service/GridData.php',
	'tx_vidi_viewhelpers_abstractviewhelper' => $extensionClassesPath . 'ViewHelpers/AbstractViewHelper.php',
	'tx_vidi_viewhelpers_includecssfileviewhelper' => $extensionClassesPath . 'ViewHelpers/IncludeCssFileViewHelper.php',
	'tx_vidi_viewhelpers_extdirectproviderviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/ExtDirectProviderViewHelper.php',
	'tx_vidi_viewhelpers_be_modulecontainerviewhelper' => $extensionClassesPath . 'ViewHelpers/Be/ModuleContainerViewHelper.php',
	'tx_vidi_service_moduleloader' => $extensionClassesPath . 'Service/ModuleLoader.php'
);
?>